base:
  project_name: ml_project
  random_state: 42
  target: Price

data_source:
  raw_data_path: data/raw/car_price_prediction.csv

load_data:
  clean_data: data/processed/car_price_prediction_clean.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.2

estimator:
  LinearRegression:
    params:
      fit_intercept: True
    
model_path: models/models.joblib

reports:
  params: reports/params.json
  score: reports/scores.json

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: car_price_prediction
  run_name: mlops
  registered_model_name: LinearRegression
  remote_server_uri: http://127.0.0.1:5000

